#SPDX-License-Identifier: ISC

obj-$(CONFIG_MT7615E) += mt7615e.o
obj-$(CONFIG_MT7622_WMAC) += mt7622-wmac.o

mt7615e-y := pci.o init.o dma.o eeprom.o main.o mcu.o mac.o \
	     debugfs.o

mt7622-wmac-y := soc.o init.o dma.o eeprom.o main.o mcu.o mac.o \
	     debugfs.o
